#!/bin/bash
# Fetch all 53 Claude Code docs using webReader
# Output: JSON file with all docs ready for ingestion

ALL_DOCS=(
  "overview|https://code.claude.com/docs/en/overview"
  "quickstart|https://code.claude.com/docs/en/quickstart"
  "setup|https://code.claude.com/docs/en/setup"
  "skills|https://code.claude.com/docs/en/skills"
  "cli-reference|https://code.claude.com/docs/en/cli-reference"
  "slash-commands|https://code.claude.com/docs/en/slash-commands"
  "mcp|https://code.claude.com/docs/en/mcp"
  "plugins|https://code.claude.com/docs/en/plugins"
  "plugins-reference|https://code.claude.com/docs/en/plugins-reference"
  "discover-plugins|https://code.claude.com/docs/en/discover-plugins"
  "plugin-marketplaces|https://code.claude.com/docs/en/plugin-marketplaces"
  "sub-agents|https://code.claude.com/docs/en/sub-agents"
  "memory|https://code.claude.com/docs/en/memory"
  "common-workflows|https://code.claude.com/docs/en/common-workflows"
  "troubleshooting|https://code.claude.com/docs/en/troubleshooting"
  "settings|https://code.claude.com/docs/en/settings"
  "hooks-guide|https://code.claude.com/docs/en/hooks-guide"
  "hooks|https://code.claude.com/docs/en/hooks"
  "checkpointing|https://code.claude.com/docs/en/checkpointing"
  "data-usage|https://code.claude.com/docs/en/data-usage"
  "monitoring-usage|https://code.claude.com/docs/en/monitoring-usage"
  "analytics|https://code.claude.com/docs/en/analytics"
  "costs|https://code.claude.com/docs/en/costs"
  "security|https://code.claude.com/docs/en/security"
  "legal-and-compliance|https://code.claude.com/docs/en/legal-and-compliance"
  "sandboxing|https://code.claude.com/docs/en/sandboxing"
  "network-config|https://code.claude.com/docs/en/network-config"
  "terminal-config|https://code.claude.com/docs/en/terminal-config"
  "model-config|https://code.claude.com/docs/en/model-config"
  "output-styles|https://code.claude.com/docs/en/output-styles"
  "statusline|https://code.claude.com/docs/en/statusline"
  "interactive-mode|https://code.claude.com/docs/en/interactive-mode"
  "headless|https://code.claude.com/docs/en/headless"
  "claude-code-on-the-web|https://code.claude.com/docs/en/claude-code-on-the-web"
  "third-party-integrations|https://code.claude.com/docs/en/third-party-integrations"
  "iam|https://code.claude.com/docs/en/iam"
  "llm-gateway|https://code.claude.com/docs/en/llm-gateway"
  "amazon-bedrock|https://code.claude.com/docs/en/amazon-bedrock"
  "google-vertex-ai|https://code.claude.com/docs/en/google-vertex-ai"
  "microsoft-foundry|https://code.claude.com/docs/en/microsoft-foundry"
  "github-actions|https://code.claude.com/docs/en/github-actions"
  "gitlab-ci-cd|https://code.claude.com/docs/en/gitlab-ci-cd"
  "devcontainer|https://code.claude.com/docs/en/devcontainer"
  "vs-code|https://code.claude.com/docs/en/vs-code"
  "jetbrains|https://code.claude.com/docs/en/jetbrains"
  "chrome|https://code.claude.com/docs/en/chrome"
  "desktop|https://code.claude.com/docs/en/desktop"
  "slack|https://code.claude.com/docs/en/slack"
)

echo "This script requires webReader MCP tool to fetch content."
echo "Total docs to fetch: ${#ALL_DOCS[@]}"
echo ""
echo "Usage: Run this via Claude with webReader tool access"
echo "Each doc needs: mcp__web_reader__webReader(url=\"${ALL_DOCS[0]/*|}\")"
